### ISSUE TITLE
remove ipv6 restrictions

### ISSUE THREAD

**Issue by malud** [coupergateway/couper#683]
Go is able to handle this but we have restricted the bind and (backend) connect options to ipv4 for simplicity. I guess we could just allow this format and create an option to disable the ipv6 bindings and connections.

**Update**: So the discussion below leads to the following config proposal:

This applies to the `server {}` block(s) bindings:

```hcl
# environment: COUPER_BIND_ADDRESS="0.0.0.0,10.1.0.22"
# cli: -bind-address=0.0.0.0,10.1.0.22
settings {
  # default: * means both types, all interfaces
  # :: just v6
  # 0.0.0.0 just v4
  # 10.1.0.22 a very specific one, who knows...
  bind_address = ["*", "::", "0.0.0.0", "10.1.0.22"]
}
```

for the outgoing backend connection configuration:

```hcl
# per backend block
backend {
  ivp6 = true
}

# for all backends
settings {
  #environment: COUPER_BACKEND_IPV6=true
  #cli: -backend-ipv6
  backend_ipv6 = true
}

The all backends option will override the specific ones.

**Comment by filex** [comment]
Yes, we should remove that. When using Couper during development on a local machine (in my case MacOS), `localhost` is often preferably resolved to its IPv6 IP. That leads to surprising "connection refused" errors when using e.g. `http://localhost:8080` instead of `http://127.0.0.1:8080`. This happens for example if an SPA server like webpack or vite proxy an API path to Couper. It would be good to be able to use `localhost` for that config.

**Comment by filex** [comment]
Which kind of configuration would we provide?
* a general settings/switch to disable ivp6 if not desired? 
* independent switches for listening and backends?
* on per-backend basis in hcl?

this depends on how likely it is that IPv6 causes problems.

**Comment by malud** [comment]
For the `server {}` part I would say let's add a more generic setting:

```hcl
settings {
  # default: * means both types, all interfaces
  # :: just v6
  # 0.0.0.0 just v4
  # 10.1.0.22 a very specific one, who knows...
  bind_address = ["*", "::", "0.0.0.0", "10.1.0.22"]
}
 ```

and for the backend part I would use a per backend configuration:

```hcl
backend {
  # so it would not break(?) existing setups
  # also a rare case while living in the pod world, use-case: wan origins
  use_ipv6 = true
}
```

**Comment by filex** [comment]
How could I add multiple bind IPs on the CLI?

```
$ couper run --bind ::,0.0.0.0
$ couper run --bind :: --bind 0.0.0
```

**Comment by malud** [comment]
I would suggest comma separated since it aligns best with the environment equivalent.

**Comment by filex** [comment]
So `backend.use_ipv6` would default to `false`?

**Comment by malud** [comment]
> So `backend.use_ipv6` would default to `false`?

yes.

**Comment by filex** [comment]
would it be useful to have a global `use_ipv6` switch, too? to make all backends use ipv6 without cluttering the whole config. That setting _could_ also affect IP binding implicitly.

________________________________________
Von: Marcel Ludwig ***@***.***>
Gesendet: Dienstag, 28. Februar 2023 09:54
An: avenga/couper
Cc: Felix Hassert; Comment
Betreff: Re: [avenga/couper] remove ipv6 restrictions (Issue #683)

So backend.use_ipv6 would default to false?

yes.

**Comment by malud** [comment]
> would it be useful to have a global `use_ipv6` switch, too? to make all backends use ipv6 without cluttering the whole config. That setting _could_ also affect IP binding implicitly.

I would go with a global backend switch which does not affect the bind options.

**Comment by filex** [comment]
How would we call that switch? `--backend-ipv6` and `COUPER_BACKEND_IPV6=true`. I think it is good to have the „backend“ prefix in the switch. But „use“ seems too verbose here. Should we use `backend.ipv6 = true` in the config, too?

**Comment by malud** [comment]
sounds good. I will update the description.

**Comment by malud** [comment]
Update done. So we do not want to enable `-backend-ipv6` for all backend and disable this for a single one?
```hcl
backend {
  ipv6 = false
}
```
Technically we could check for the existing attribute (syntax or bool ptr).

**Comment by alex-schneider** [comment]
The outgoing backend connection uses/supports already both IPv4 and IPv6.

We need not the `backend_ipv6 = true` in the settings and in the backend block...

**Comment by filex** [comment]
> The outgoing backend connection uses/supports already both IPv4 and IPv6.

Ah, really? So if that is not a change, then I would agree that we don't need to make it configureable now.

________________________________________
Von: Alex Schneider ***@***.***>
Gesendet: Donnerstag, 6. April 2023 11:11
An: avenga/couper
Cc: Felix Hassert; Comment
Betreff: Re: [avenga/couper] remove ipv6 restrictions (Issue #683)

The outgoing backend connection uses/supports already both IPv4 and IPv6.

We need not the backend_ipv6 = true in the settings and in the backend block...

**Comment by rcanavan** [comment]
Does it use https://en.wikipedia.org/wiki/Happy_Eyeballs for outgoing connections?

**Comment by filex** [comment]
We use the resolver/dialer from the standard Go lib. AFAIK, it does a dial race for ipv4/6.

________________________________________
Von: rcanavan ***@***.***>
Gesendet: Donnerstag, 6. April 2023 12:51
An: avenga/couper
Cc: Felix Hassert; Comment
Betreff: Re: [avenga/couper] remove ipv6 restrictions (Issue #683)

Does it use https://en.wikipedia.org/wiki/Happy_Eyeballs for outgoing connections?
