### ISSUE TITLE
Watch roles_map_file when started in watch mode

### ISSUE THREAD

**Issue by kevinsandow** [coupergateway/couper#818]
At the moment watch mode only watches config files. In our use case we frequently change the role map during development.

If the role map was inlined in the config that would already work, but we want to use the feature to make the role map its own file.

Please watch those files as well, so we don't have to manually restart couper.

**Comment by malud** [comment]
Thanks @kevinsandow. #747 has been merged a while ago. Could you please check if the edge/master version works as expected in your case?

**Comment by johakoch** [comment]
See also https://github.com/coupergateway/couper/issues/697. Actually, I don't remember which attributes are affected by the fix implemented there...

**Comment by johakoch** [comment]
@kevinsandow Looks like this is already implemented in master, at least if you change the contents of an already existing file referenced by `roles_map_file` (and not change between `roles_map_file` and `roles_map`).
